#!/bin/bash

set -ev

CURRENT_WORKING_BRANCH=$BETA_RELEASE_BRANCH

git checkout $CURRENT_WORKING_BRANCH
git remote set-url origin https://${GITHUB_TOKEN}@github.com/georgeracu/947g5.git
git merge master
npm version patch --no-git-tag-version --allow-same-version
git add package.json
git add package-lock.json
GIT_TAG_VERSION=$(jq -r '.version' package.json)
git commit -m "Setting version to $GIT_TAG_VERSION via Travis CI"
git push origin $CURRENT_WORKING_BRANCH 2>&1
echo "Finished patching release version"