# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform :ios

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(workspace: "MyAwesomeApp.xcworkspace", scheme: "MyAwesomeAppUITests")
  end

  desc "Run all tests"
  lane :tests do
    run_tests(scheme: "MyAwesomeApp")
  end

  desc "Do Beta deployment to Firebase App Distribution"
  lane :beta do
    # add actions here: https://docs.fastlane.tools/actions
    build_app(scheme: "MyAwesomeApp")
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    slack(message: "Lane ios #{lane} ran successfully")
  end

  error do |lane, exception|
    slack(
        message: "There was an exception on lane ios #{lane} with message #{exception.message}",
        success: false
    )
  end
end
